### PR TITLE
WIP: Optimize the storefront-springboot-pl 

### PR DESCRIPTION
**Pull request by kitty-catt**
This is an experimental pipeline which uses:
- a shared workspace for git-source;
- a different shared workspace for a local maven-repo;

Both workspaces are on a seperate PV via a seperate PVC.

The first time that the pipeline has a run, it will initialize the local maven repo.

The next time that the pipeline has a run, it already has the maven artifacts it needs, it then runs considerably faster. 

The pipeline run example is in the pipelinerun example. It supplies the workspaces via the claim. Perhaps that can be changed in the a future edition.

Good luck!

kitty-catt

### CODE REVIEW

**Comment by csantanapr** [comment]
## Tekton Status Report 

Status | Pipeline | PipelineRun | Namespace
:----- | :------- | :--------------- | :--------
**Missing** | N/A | No PipelineRuns were ever detected, failing the build | N/A

**Comment by oiricaud** [comment]
Great job! Ronald! Love it, thanks for contributing 

I want to ensure a few things first we currently have two pipelines, `storefront-springboot` and `storefront-nodejs` and these pipelines essentially do the following tasks: 

Screen Shot 2020-08-27 at 7 46 42 AM

If your goal is to improve the speed of these pipelines,  `storefront-springboot` and `storefront-nodejs` then you will to ensure that our tasks that we created are still there.

**Comment by oiricaud** [comment]
I encourage you to use the `storefront-springboot` as a backbone, and add the workspaces and pvc you added on this newly pipeline to see if you improved the speed of the pipeline.

From my understanding, you recognized that for each pipeline run you download the maven binaries to compile the application, you noticed that this is redundant. So what you did you downloaded container storage, created persistent volume claim for the maven binaries, which is connected to the workspace. Then you use this workspace for a local maven repo.

**Comment by oiricaud** [comment]
To-do items
- [ ] Use this repository/toolbox to add our existing pipelines to your environment

- [ ] Integrate the changes on this pull request on the `storefront-springboot-pl` to determine if you can optimize the speed of the pipelinerun using workspaces and pvc

- [ ] Verify and Validate the `storefront-springboot-pl` still functions :)

**Comment by oiricaud** [comment]
This is an example of an existing issue we have - https://github.com/ibm-garage-ref-storefront/planning/issues/30

**Pull request closed without merging**
